[project]
name = "fastapi-tortoise-aerich-demo"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aerich>=0.9.2",
    "asynctor>=0.12.11",
    "fastapi[standard]>=0.136.3",
    "tortoise-orm[asyncpg,accel]>=1.1.7",
]

[tool.uv.sources]
aerich = { git = "https://github.com/tortoise/aerich" }

[dependency-groups]
dev = [
    "mypy>=2.1.0",
    "tomlkit>=0.15.0",
    "typer>=0.19.1",
]

[tool.pdm.version]
path = "app/__init__.py"

[tool.pdm]
distribution = false

[tool.uv]
package = false

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.tortoise]
tortoise_orm = "app.settings.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[tool.mypy]
pretty = true
python_version = "3.11"
exclude = ["migrations/", ".venv"]
