[program:fastapi_app]
command=uv run --no-config --no-cache --no-sync gunicorn app.main:app -c deployment/gunicorn_config.py
directory=/home/ubuntu/coding/fastapi-tortoise-aerich-demo
stdout_logfile=/home/ubuntu/coding/fastapi-tortoise-aerich-demo/logs/supervisor.log

numprocs=1
autostart=true
startsecs=10
autorestart=true
startretried=3
redirect_stderr=true
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=20

